//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActorMovieTwelve
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Actor = new HashSet<Actor>();
        }
    
        public int MovieId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Year { get; set; }
        public string MovieDescription { get; set; }
        public Nullable<int> Category1Id { get; set; }
        public Nullable<int> Category2Id { get; set; }
        public string Country { get; set; }
        public string PosterImage { get; set; }
    
        public virtual ICollection<Actor> Actor { get; set; }
    }
}
