//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 4/27/2013 3:42:34 PM
namespace ActorMovieGrid.ActorMovieServiceReference
{
    
    /// <summary>
    /// There are no comments for martinbeEntities in the schema.
    /// </summary>
    public partial class martinbeEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new martinbeEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public martinbeEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("martinbeModel", global::System.StringComparison.Ordinal))
            {
                return global::System.Reflection.IntrospectionExtensions.GetTypeInfo(this.GetType()).Assembly.GetType(string.Concat("ActorMovieGrid.ActorMovieServiceReference", typeName.Substring(13)));
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ActorMovieGrid.ActorMovieServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("martinbeModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Actor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Actor> Actor
        {
            get
            {
                if ((this._Actor == null))
                {
                    this._Actor = base.CreateQuery<Actor>("Actor");
                }
                return this._Actor;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Actor> _Actor;
        /// <summary>
        /// There are no comments for Movie in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Movie> Movie
        {
            get
            {
                if ((this._Movie == null))
                {
                    this._Movie = base.CreateQuery<Movie>("Movie");
                }
                return this._Movie;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Movie> _Movie;
        /// <summary>
        /// There are no comments for Actor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToActor(Actor actor)
        {
            base.AddObject("Actor", actor);
        }
        /// <summary>
        /// There are no comments for Movie in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMovie(Movie movie)
        {
            base.AddObject("Movie", movie);
        }
    }
    /// <summary>
    /// There are no comments for martinbeModel.Actor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ActorId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Actor")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ActorId")]
    public partial class Actor : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Actor object.
        /// </summary>
        /// <param name="actorId">Initial value of ActorId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Actor CreateActor(int actorId)
        {
            Actor actor = new Actor();
            actor.ActorId = actorId;
            return actor;
        }
        /// <summary>
        /// There are no comments for Property ActorId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ActorId
        {
            get
            {
                return this._ActorId;
            }
            set
            {
                this.OnActorIdChanging(value);
                this._ActorId = value;
                this.OnActorIdChanged();
                this.OnPropertyChanged("ActorId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ActorId;
        partial void OnActorIdChanging(int value);
        partial void OnActorIdChanged();
        /// <summary>
        /// There are no comments for Property Firstname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Firstname
        {
            get
            {
                return this._Firstname;
            }
            set
            {
                this.OnFirstnameChanging(value);
                this._Firstname = value;
                this.OnFirstnameChanged();
                this.OnPropertyChanged("Firstname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Firstname;
        partial void OnFirstnameChanging(string value);
        partial void OnFirstnameChanged();
        /// <summary>
        /// There are no comments for Property Middlename in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Middlename
        {
            get
            {
                return this._Middlename;
            }
            set
            {
                this.OnMiddlenameChanging(value);
                this._Middlename = value;
                this.OnMiddlenameChanged();
                this.OnPropertyChanged("Middlename");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Middlename;
        partial void OnMiddlenameChanging(string value);
        partial void OnMiddlenameChanged();
        /// <summary>
        /// There are no comments for Property Lastname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Lastname
        {
            get
            {
                return this._Lastname;
            }
            set
            {
                this.OnLastnameChanging(value);
                this._Lastname = value;
                this.OnLastnameChanged();
                this.OnPropertyChanged("Lastname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Lastname;
        partial void OnLastnameChanging(string value);
        partial void OnLastnameChanged();
        /// <summary>
        /// There are no comments for Property Birthday in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return this._Birthday;
            }
            set
            {
                this.OnBirthdayChanging(value);
                this._Birthday = value;
                this.OnBirthdayChanged();
                this.OnPropertyChanged("Birthday");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
                this.OnPropertyChanged("Image");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property About in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string About
        {
            get
            {
                return this._About;
            }
            set
            {
                this.OnAboutChanging(value);
                this._About = value;
                this.OnAboutChanged();
                this.OnPropertyChanged("About");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _About;
        partial void OnAboutChanging(string value);
        partial void OnAboutChanged();
        /// <summary>
        /// There are no comments for Movie in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Movie> Movie
        {
            get
            {
                return this._Movie;
            }
            set
            {
                this._Movie = value;
                this.OnPropertyChanged("Movie");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Movie> _Movie = new global::System.Data.Services.Client.DataServiceCollection<Movie>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for martinbeModel.Movie in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MovieId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Movie")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MovieId")]
    public partial class Movie : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Movie object.
        /// </summary>
        /// <param name="movieId">Initial value of MovieId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Movie CreateMovie(int movieId)
        {
            Movie movie = new Movie();
            movie.MovieId = movieId;
            return movie;
        }
        /// <summary>
        /// There are no comments for Property MovieId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int MovieId
        {
            get
            {
                return this._MovieId;
            }
            set
            {
                this.OnMovieIdChanging(value);
                this._MovieId = value;
                this.OnMovieIdChanged();
                this.OnPropertyChanged("MovieId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _MovieId;
        partial void OnMovieIdChanging(int value);
        partial void OnMovieIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this._Year = value;
                this.OnYearChanged();
                this.OnPropertyChanged("Year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Year;
        partial void OnYearChanging(global::System.Nullable<int> value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Property MovieDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MovieDescription
        {
            get
            {
                return this._MovieDescription;
            }
            set
            {
                this.OnMovieDescriptionChanging(value);
                this._MovieDescription = value;
                this.OnMovieDescriptionChanged();
                this.OnPropertyChanged("MovieDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MovieDescription;
        partial void OnMovieDescriptionChanging(string value);
        partial void OnMovieDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Category1Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Category1Id
        {
            get
            {
                return this._Category1Id;
            }
            set
            {
                this.OnCategory1IdChanging(value);
                this._Category1Id = value;
                this.OnCategory1IdChanged();
                this.OnPropertyChanged("Category1Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Category1Id;
        partial void OnCategory1IdChanging(global::System.Nullable<int> value);
        partial void OnCategory1IdChanged();
        /// <summary>
        /// There are no comments for Property Category2Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Category2Id
        {
            get
            {
                return this._Category2Id;
            }
            set
            {
                this.OnCategory2IdChanging(value);
                this._Category2Id = value;
                this.OnCategory2IdChanged();
                this.OnPropertyChanged("Category2Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Category2Id;
        partial void OnCategory2IdChanging(global::System.Nullable<int> value);
        partial void OnCategory2IdChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property PosterImage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PosterImage
        {
            get
            {
                return this._PosterImage;
            }
            set
            {
                this.OnPosterImageChanging(value);
                this._PosterImage = value;
                this.OnPosterImageChanged();
                this.OnPropertyChanged("PosterImage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PosterImage;
        partial void OnPosterImageChanging(string value);
        partial void OnPosterImageChanged();
        /// <summary>
        /// There are no comments for Actor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Actor> Actor
        {
            get
            {
                return this._Actor;
            }
            set
            {
                this._Actor = value;
                this.OnPropertyChanged("Actor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Actor> _Actor = new global::System.Data.Services.Client.DataServiceCollection<Actor>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
